my.email: tiendat.1392.hvact@gmail.com
my.password: Dat1392@

spring:
  datasource:
    url: jdbc:postgresql://$(PROD_DB_HOST):$(PROD_DB_PORT)/$(PROD_DB_NAME)
    username: $(PROD_DB_USERNAME)
    password: $(PROD_DB_PASSWORD)
    name:spring-topcv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true